### ISSUE TITLE
Ahnentafel: null displayed in name

### ISSUE THREAD

**Issue by PeWu** [wikitree/wikitree-dynamic-tree#105]
**Describe the bug**
"null" is displayed as part of the name of an ancestor in the ahnentafel view

**To Reproduce**
https://www.wikitree.com/treewidget/Wi%C4%99ch-17/7#name=Wi%C4%99ch-17&view=ahnentafel

**Screenshots**
![image](https://user-images.githubusercontent.com/6564445/201541764-333d6016-8279-473c-ae12-a5f0080c3764.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome

**Comment by bcaseyrls** [comment]
Fixed (by simple expedient of checking for null MiddleName rather than the larger task of incorporating a generalized Profile Name utility).

**Comment by sandos** [comment]
This should be closed?

**Comment by jmegenealogy** [comment]
Completed: https://github.com/wikitree/wikitree-dynamic-tree/commit/510805030fbe013a49750ab6a9626f2957c6eeb8
