### ISSUE TITLE
Portraits view continues processing images even when navigating to new views

### ISSUE THREAD

**Issue by harrislineage** [wikitree/wikitree-dynamic-tree#185]
**Describe the bug**
When navigating away from the portraits view, the process is not stopped and images continue to load to new views.

**To Reproduce**
1. Go to '[Portraits view as Clarke-1107](https://apps.wikitree.com/apps/wikitree-dynamic-tree/#name=Clarke-11007&view=portraits)' (needs pagination in getPeople to retreive all ancestors
2. Ass soon as images start to display, navigate to any other view
4. See error - images continue to load from portraits app, either overlapping or below new view content

**Expected behavior**
Portraits view should stop processing on view change, possibly using close event?

**Screenshots**
![image](https://github.com/wikitree/wikitree-dynamic-tree/assets/80127898/c63afbc0-0f7f-46c0-9ef0-98fdf38a2ced)

**Comment by udjeni** [comment]
You might know this already, but there is a close() method on View() that you can implement in your derived View class to then  abort your API call using javascript's AbortController.
