### ISSUE TITLE
Include the BioCheck information in the CC7 Views Excel download

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-dynamic-tree#194]
A user can choose to have BioCheck run on the CC7 Views app. 

It has been requested that the BioCheck information be included in the Excel download. See https://www.wikitree.com/g2g/1648839/wikitree-hacktoberfest-2023-testing-and-feedback-requests?show=1653720#c1653720 .

**Comment by udjeni** [comment]
See https://github.com/wikitree/wikitree-dynamic-tree/pull/198
