### ISSUE TITLE
View that displays all the portraits of your ancestors.

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-dynamic-tree#20]
From a [G2G](https://www.wikitree.com/g2g/964400/portraits-of-your-ancestors) post:

> WikiTree can easily show all one’s ancestors.  Is it possible for WikiTree to automatically generate a page of portraits of those ancestors?  For example, if an image is in the image field then that image is displayed.
>
> I’m already doing this manually but I keep having to update as others in our collaborative tree revise who my early ancestors were.
>
> I’m talking about going beyond something like https://www.wikitree.com/treewidget/Arbuthnot-53/4 by making use of something like http://wikitree.sdms.si/function/WTWebAncestors/errors.htm?WikiTreeID=Roberts-7085

**Comment by bcaseyrls** [comment]
Gathering ancestors is straight-forward with the API, either using getAncestors() or recursively doing getProfile() on the mother/father ids. I used the latter approach in the Ahnentafel view. Code like that view could easily add portraits to a list of ancestors just by getting the PhotoData field for the gathered profiles.
