### ISSUE TITLE
newTree functionality broken (link inside popup)

### ISSUE THREAD

**Issue by Clarke-11007** [wikitree/wikitree-dynamic-tree#35]
The pop-up on the Dynamic Tree (which shows more details about the person you've clicked on - full dates and locations, not just lifespan) - has an Ancestor Tree icon - that USED to auto-load the Dynamic Tree for that person as the primary person.

I used the same functionality (it came for free without me doing anything) for the Fan Chart.   

It now seems to be broken in both places.  According to console.log, the function that it is trying to call is newTree() - but - that function doesn't seem to exist anymore.
actual code is this:  <a onClick="newTree('${person.getName()}');" href="#">

**Comment by MichalVasut** [comment]
ouch, this seems to be my mistake 😭 ...

https://github.com/wikitree/wikitree-dynamic-tree/search?q=newTree

Those popups calls `onClick="newTree('${person.getName()}');"` and those are gone since my refactor.

I'll fix it tonight.

**Comment by bcaseyrls** [comment]
@MichalVasut fixed this. We can load new views with links to "#name=WikiTreeID&view=ViewID".

**Comment by MichalVasut** [comment]
> @MichalVasut fixed this. We can load new views with links to "#name=WikiTreeID&view=ViewID".

when you want to reload only person and the view should stay the same, just `#name=WikiTreeID` is enough - ckeck the example https://github.com/wikitree/wikitree-dynamic-tree/blob/main/views/baseDynamicTree/WikiTreeDynamicTreeViewer.js#L430
