### ISSUE TITLE
Don't add links to ancestors that aren't displayed in the Ahnentafel list.

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-dynamic-tree#41]
From [G2G](https://www.wikitree.com/g2g/1481431/wikitree-hacktoberfest-2022-bug-reports?show=1481793#a1481793):

> The "Ahnentafel Ancestor List for Elizabeth Alexandra Mary Windsor - Windsor-1" goes to line 127. Each line contains numbers which are links, e.g. number 255 links to https://apps.wikitree.com/apps/wikitree-dynamic-tree/#255   If the number in the link is <= 127, clicking scrolls to and highlights that row: correct. But if the number is > 127, clicking the link does nothing (because there is no such row). Shouldn't the link be suppressed in those cases, with just a plain number shown instead?

**Comment by bcaseyrls** [comment]
This is addressed (along with a performance boost from getAncstors) in https://github.com/wikitree/wikitree-dynamic-tree/pull/72. Note that the links themselves are broken; I'm creating a separate issue for that.
