### ISSUE TITLE
Write more complete documentation on how to create a new view.

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-dynamic-tree#5]
This should probably be in a separate file from the README.

**Comment by bcaseyrls** [comment]
Thanks, Michal! As we move forward with (hopefully) lots of new views, I think trying to normalize how they appear and are added to the overal project will be helpful. The current setup keeps everything pretty separate -- each view is just its own JS file with a function that gets called by launchTree(). There's a simplicity in that, I think, that makes it easy to add new things. But providing a scaffolding through a View class has definite advantages too. I think it's an effort worth pursuing.


- Brian

**Comment by MichalVasut** [comment]
Thanks for answer, yes, definitely, the views will be in separate files and folders as they are know. That little demo is in one file only for faster work and it needs some work.

**Comment by Clarke-11007** [comment]
Can we see this in action ?

As I begin to move my Fan Chart app to this framework, I'm wondering if I
could also make use of the views?  For that to work, I'd have to be able to
rotate each person's info at a different angle - either parallel or
perpendicular to the "spokes" of the fan chart extruding from the centre.
Is that possible with your work Michal - or - would it be after a potential
future update?

I can see the value in a common "view" module / class - whatever we call it
- so the different views can benefit from that consistency of information
and display, while each focusing on the logistics of how to arrange it on
the screen.

 - Greg
:-)

**Comment by MichalVasut** [comment]
Please don't move it yet (or move to the old framework), it's still only first draft, just for preview and approval for future work.  

Currently it only loads some testing views and I'm trying to convert Dynamic Tree view to this framework, so no working example yet, you can pull the branch and test it, but it doesn't even look good 🙃 .

**Comment by Clarke-11007** [comment]
OK - thanks for the warning ... when I start my work on the Fan Chart (it's
going to look real ugly for a while I can assure you!) - I'll use a
simplistic view to start with, hoping that eventually I'll be able to swap
in something that will work later on.

Thanks for doing this Michal!

  -Greg
:-)

**Comment by MichalVasut** [comment]
I've just extracted login functionality in my branch into separate class that could imho be used enywhere.

Features
- standalone - takes care about login process and handling cookies
- no additional redirect after receiving `code`
- posibble to attach some ecents 
    - `onLoggedIn(user)` - the `user` parameter is of class `WTUser` containg `id`,`name` and method `isLoggedIn()`
    - `onAuthFail()`
    - `onUnlogged()`

**Comment by MichalVasut** [comment]
New registration of views is complete and working - well, at least from technical point of view - still needs some love to make it prettier and usable from visual point of view, therefore I'll leave it in draft, till it's improved.

Here is come manual how to create & register new view (it'll be maybe better to move it into some .md file )
- https://github.com/wikitree/wikitree-dynamic-tree/pull/11/files#diff-fdad57d1a241d8ee9559ff5b2e521c742e7039793bf6e50dede90c1378d38f22R27 

Here is the "beast" (aka ViewRegistry)
- https://github.com/wikitree/wikitree-dynamic-tree/pull/11/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R47

PS: I've also added some formatting config (`.prettierrc`), to keep the file in some form - the config can be used in more ways
- locally e.g. for VS Code addon to format the code
- for Github Action to format the code automatically when pushed to repo

**Comment by MichalVasut** [comment]
It seems to be ready, live preview is here (@Clarke-11007  you can test it)

https://apps.wikitree.com/apps/vasut2/views-registry/

Some docs rewrite is needed, but it works

**Comment by Clarke-11007** [comment]
Thanks Michal, will do!

Greg

**Comment by MichalVasut** [comment]
btw, here is another (more compact design), that shows more of the view - it's just quick play with the propertis in browser (not saved)

![image](https://user-images.githubusercontent.com/20949562/194069200-726a474b-3bcc-44ec-8721-93725deb0e1a.png)

vs current design in my branch

![image](https://user-images.githubusercontent.com/20949562/194069660-753587bf-3e1c-4268-b139-a2367b1af825.png)

**Comment by MichalVasut** [comment]
@bcaseyrls isn't this solved with my last pull request and also your previous work?

https://github.com/wikitree/wikitree-dynamic-tree/blob/main/contributing.md

**Comment by bcaseyrls** [comment]
Yes, I think so (though I should go back over the contributing docs again with a fresh eye).
