### ISSUE TITLE
Removal of the `master` branch

### ISSUE THREAD

**Issue by MichalVasut** [wikitree/wikitree-dynamic-tree#56]
Is it possible to remove the `master` branch from this repo? 

There is default `main` branch and every time, I must rebase (due to unevitable conflicts), it confuses me a lot and I must check every time what is the correct branch.

**Comment by bcaseyrls** [comment]
Yes, removal was always the plan. It was left for a time after the creation of main as the new default because of the existing pull request (couples view).
