### ISSUE TITLE
Add the functionality of the Printer-Friendly Tree view.

### ISSUE THREAD

**Issue by jmegenealogy** [wikitree/wikitree-dynamic-tree#7]
This is the view you get when you click "Printer-Friendly Tree" on the Family Tree & Tools page.

For example, https://www.wikitree.com/treewidget/Adams-35/100.

**Comment by MichalVasut** [comment]
> This is the view you get when you click "Printer-Friendly Tree" on the Family Tree & Tools page.
> 
> For example, https://www.wikitree.com/treewidget/Adams-35/100.

Is the issue solved, when there is already the example or what's the point of this?

**Comment by jmegenealogy** [comment]
The point is to create a version that uses the API and can be edited by others.

**Comment by MichalVasut** [comment]
This is better, but if I may suggest, to rephrase this and other tasks to be more specific like:

> Recreate `Printer-friendly treeview` to use REST API and user defined templates.
> You may take inspiration from current implementation: ... 


Or something like this.

**Comment by MichalVasut** [comment]
Well, I'm still little bit confused :-D ... When I've mentioned that there is already some code, it was in different project - [wikitree-extension - Printer friendly feature](https://github.com/wikitree/wikitree-browser-extension/tree/development/features/printerfriendly) - which is entirely something different.

I must tak step back and ask again - What is the goal of this task?

To create Printable & Customizable version of this (Dynamic tree)[https://www.wikitree.com/treewidget/Windsor-1/7]?

You can already print it via CTRL+P (or Mac alternative, or via menu), but the result is the complete page, not only the treeview itself.

Well, it was almost night yesterday so I was little bit slower and I hope I've grasped it right this time 😄

**Comment by harrislineage** [comment]
> I must tak step back and ask again - What is the goal of this task?
> 
> To create Printable & Customizable version of this [Dynamic tree](https://www.wikitree.com/treewidget/Windsor-1/7)?

@MichalVasut No, that is the Dynamic Tree View.

There are a series of tree **views and tools** available under the "Family Trees & Tools" tab of each profile. For reference, check your own tree views that are [available here](https://www.wikitree.com/genealogy/Va%C5%A1ut-Family-Tree-2).

Many of these views are provided by WikiTree through page templates, and the code is not opensource and cannot be collaborated on by others. This entire github repository, also called wikitree-dynamic-tree and may be leading to confusion, is a project to make these tree views opensource collaborative code.

This task we are commenting on is focusing on [this specific tree view](https://www.wikitree.com/treewidget/Adams-35/100).

**Comment by harrislineage** [comment]
I will create a branch to begin work on this.

**Comment by harrislineage** [comment]
@MichalVasut There are two different things going on here.

The browser-extension contains a [Printer Friendly **Biography**](https://github.com/wikitree/wikitree-browser-extension/blob/development/features/printerfriendly/printerfriendly.js) option.

The issue opened here (this thread) under the dynamic-tree is not for the biography - but for the tree view located here: https://www.wikitree.com/treewidget/Adams-35/100

**Comment by MichalVasut** [comment]
Ok, all clear now. Thanks.

**Comment by MichalVasut** [comment]
OK, I'll do that, thanks for answer.

**Comment by MichalVasut** [comment]
@bcaseyrls This can be probably closed, right?
