### ISSUE TITLE
Provide for API logout

### ISSUE THREAD

**Issue by bcaseyrls** [wikitree/wikitree-dynamic-tree#80]
We store local to the app cookies to remember that a user is signed into the API. But we do not provide a way for a user to logout (or change the user they are signed in under). If the cookies at api.wikitree.com ever get out of sync with those at the app hostname (e.g. apps.wikitree.com), then the user has to clear the cookies on both hostnames (or all cookies, but that can be irritating).

We need the API to have a "sign out" function. Then we should implement it in the tree (maybe a simple "X" link in the "Logged into API" label).

**Comment by bcaseyrls** [comment]
The API function is in QA. Once ready, we can implement in the tree.

**Comment by MichalVasut** [comment]
@bcaseyrls This also seems to be done?

https://github.com/wikitree/wikitree-api/blob/e0639fa7a1c3f1c8bb47d9db3a9ccadee797a601/authentication.md#logging-out
